### ISSUE TITLE
Problem with running some test scripts.

### ISSUE THREAD

**Issue by tae898** [leolani/cltl-knowledgerepresentation#3]
```
(leolani) ➜  cltl-knowledgerepresentation git:(main) python3 tests/carl.py
/home/tk/.virtualenvs/leolani/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "tests/carl.py", line 61, in <module>
    brain = LongTermMemory(address="http://localhost:7200/repositories/sandbox",
  File "/home/tk/Downloads/cltl-knowledgerepresentation/src/cltl/brain/long_term_memory.py", line 31, in __init__
    super(LongTermMemory, self).__init__(address, log_dir, clear_all)
  File "/home/tk/Downloads/cltl-knowledgerepresentation/src/cltl/brain/basic_brain.py", line 50, in __init__
    self.upload_ontology()
  File "/home/tk/Downloads/cltl-knowledgerepresentation/src/cltl/brain/basic_brain.py", line 106, in upload_ontology
    data = self._serialize(self._brain_log)
  File "/home/tk/Downloads/cltl-knowledgerepresentation/src/cltl/brain/basic_brain.py", line 89, in _serialize
    with open(f'{file_path}.{self._connection.format}', 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tk/Downloads/src/cltl/brain/logs/brain_log_2021-07-21-09-26.trig'
(leolani) ➜  cltl-knowledgerepresentation git:(main) python3 tests/famous_person_graph.py
/home/tk/.virtualenvs/leolani/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "tests/famous_person_graph.py", line 11, in <module>
    brain = FameAwareMemory(address="http://localhost:7200/repositories/sandbox",
  File "/home/tk/Downloads/cltl-knowledgerepresentation/src/cltl/brain/fame_aware.py", line 21, in __init__
    super(FameAwareMemory, self).__init__(address, log_dir, clear_all)
  File "/home/tk/Downloads/cltl-knowledgerepresentation/src/cltl/brain/long_term_memory.py", line 31, in __init__
    super(LongTermMemory, self).__init__(address, log_dir, clear_all)
  File "/home/tk/Downloads/cltl-knowledgerepresentation/src/cltl/brain/basic_brain.py", line 50, in __init__
    self.upload_ontology()
  File "/home/tk/Downloads/cltl-knowledgerepresentation/src/cltl/brain/basic_brain.py", line 106, in upload_ontology
    data = self._serialize(self._brain_log)
  File "/home/tk/Downloads/cltl-knowledgerepresentation/src/cltl/brain/basic_brain.py", line 89, in _serialize
    with open(f'{file_path}.{self._connection.format}', 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tk/Downloads/src/cltl/brain/logs/brain_log_2021-07-21-09-26.trig'
```

**Comment by tae898** [comment]
Currently I'm running the scripts from the root directory of the repo. Perhaps I should run it on somewhere else?
